/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author natha
 */
public class TelaGenio extends javax.swing.JFrame {

    /**
     * Creates new form TelaGenio
     */
    public TelaGenio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPanel1 = new javax.swing.JPanel();
        txtN2 = new javax.swing.JLabel();
        txtN3 = new javax.swing.JLabel();
        lblGuess1 = new javax.swing.JButton();
        lblGuess2 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtN2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtN2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtN2.setText("I am thinking of a value between 1 and 5.");
        txtPanel1.add(txtN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 260, -1));

        txtN3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtN3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtN3.setText("Try to guess what value and that.");
        txtPanel1.add(txtN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 212, -1));

        lblGuess1.setText("Confirm");
        lblGuess1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblGuess1ActionPerformed(evt);
            }
        });
        txtPanel1.add(lblGuess1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 80, 30));
        txtPanel1.add(lblGuess2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 60, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/akinator.png"))); // NOI18N
        txtPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 290, 430));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Value");
        txtPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 50, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/balloons text.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        txtPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 580, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGuess1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblGuess1ActionPerformed
        int guessN, Xran;
        double xran;
        xran = Math.round(1 + Math.random()*(5-1));
        Xran = (int)xran;
        guessN = Integer.parseInt(lblGuess2.getValue().toString());
        String R =(Xran==guessN)?"<html><strong>Acertou!</strong></html>":"<html><strong>Errou!</strong> pensei em "+ Xran + " </html>";
        txtN3.setVisible(false);
        txtN2.setText(R);
    }//GEN-LAST:event_lblGuess1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton lblGuess1;
    private javax.swing.JSpinner lblGuess2;
    private javax.swing.JLabel txtN2;
    private javax.swing.JLabel txtN3;
    private javax.swing.JPanel txtPanel1;
    // End of variables declaration//GEN-END:variables
}
